name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  install_dependencies_job:
    runs-on: ubuntu-latest
    name: Install Dependencies Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Install Angular CLI 16
        run: npm install -g @angular/cli@16.2.14
      - name: Install Dependencies
        run: 
          npm install @angular/animations@16.2.0 --legacy-peer-deps
          npm install @angular/cdk@16.2.14 --legacy-peer-deps
          npm install @angular/common@16.2.0 --legacy-peer-deps
          npm install @angular/compiler@16.2.0 --legacy-peer-deps
          npm install @angular/core@16.2.0 --legacy-peer-deps
          npm install @angular/forms@16.2.0 --legacy-peer-deps
          npm install @angular/material@16.2.14 --legacy-peer-deps
          npm install @angular/platform-browser@16.2.0 --legacy-peer-deps
          npm install @angular/platform-browser-dynamic@16.2.0 --legacy-peer-deps
          npm install @angular/router@16.2.0 --legacy-peer-deps
          npm install @fullcalendar/angular@6.1.14 --legacy-peer-deps
          npm install @fullcalendar/core@6.1.14 --legacy-peer-deps
          npm install @fullcalendar/daygrid@6.1.14 --legacy-peer-deps
          npm install @fullcalendar/timegrid@6.1.14 --legacy-peer-deps
          npm install angular-calendar-scheduler@16.0.0 --legacy-peer-deps
          npm install angular-scheduler@0.0.1 --legacy-peer-deps
          npm install apexcharts@3.49.1 --legacy-peer-deps
          npm install bootstrap@5.3.3 --legacy-peer-deps
          npm install date-fns@3.6.0 --legacy-peer-deps
          npm install jwt-decode@4.0.0 --legacy-peer-deps
          npm install ng-apexcharts@1.10.0 --legacy-peer-deps
          npm install primeng@16.0.1 --legacy-peer-deps
          npm install rxjs@7.8.0 --legacy-peer-deps
          npm install tslib@2.3.0 --legacy-peer-deps
          npm install zone.js@0.13.0 --legacy-peer-deps

  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    needs: install_dependencies_job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_CLIFF_0D436500F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "/" # App source code path
          api_location: "api" # Api source code path - optional
          output_location: "dist/centro-educa" # Built app content directory - optional

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_CLIFF_0D436500F }}
          action: "close"
